#include "Core/GameLog.h"

DEFINE_LOG_CATEGORY(LogGameCombat);
DEFINE_LOG_CATEGORY(LogGameAI);
DEFINE_LOG_CATEGORY(LogGameArmy);
DEFINE_LOG_CATEGORY(LogGameNav);
DEFINE_LOG_CATEGORY(LogGameEncounter);
DEFINE_LOG_CATEGORY(LogGameRun);
DEFINE_LOG_CATEGORY(LogGamePlayer);
DEFINE_LOG_CATEGORY(LogGameUI);
