#pragma once

#include "Logging/LogMacros.h"

// One category per domain: LogGame<Domain>. The Visual Logger uses the same categories.
CASTLEDEFENDER_API DECLARE_LOG_CATEGORY_EXTERN(LogGameCombat, Log, All);
CASTLEDEFENDER_API DECLARE_LOG_CATEGORY_EXTERN(LogGameAI, Log, All);
CASTLEDEFENDER_API DECLARE_LOG_CATEGORY_EXTERN(LogGameArmy, Log, All);
CASTLEDEFENDER_API DECLARE_LOG_CATEGORY_EXTERN(LogGameNav, Log, All);
CASTLEDEFENDER_API DECLARE_LOG_CATEGORY_EXTERN(LogGameEncounter, Log, All);
CASTLEDEFENDER_API DECLARE_LOG_CATEGORY_EXTERN(LogGameRun, Log, All);
CASTLEDEFENDER_API DECLARE_LOG_CATEGORY_EXTERN(LogGamePlayer, Log, All);
CASTLEDEFENDER_API DECLARE_LOG_CATEGORY_EXTERN(LogGameUI, Log, All);
CASTLEDEFENDER_API DECLARE_LOG_CATEGORY_EXTERN(LogGameFeedback, Log, All);
