#pragma once

#include "NativeGameplayTags.h"

// Native Gameplay Tags: the single definition point for tag roots (main plan §8).
// New roots require an entry in 00-foundation/technical-plan.md §18.
// Features add leaf tags under existing roots here; do not duplicate native tags in .ini files.
namespace GameTags
{
	// State.Combat: shared timed combat states (owned by UCombatStateComponent)
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Staggered);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_ArmorBroken);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Combat_Marked);

	// State.Hero
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Hero_Attacking);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Hero_Dodging);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Hero_Blocking);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Hero_Parrying);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Hero_Dead);

	// Unit
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Enemy_Melee);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Enemy_Elite);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Enemy_Swarm);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Enemy_Armored);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Enemy_Siege);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Enemy_Boss);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Squad_Infantry);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Squad_Archer);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Unit_Squad_Spearman);

	// Structure.Role
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Structure_Role_Core);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Structure_Role_Blocker);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Structure_Role_CombatTower);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Structure_Role_Utility);

	// Command
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Command_Guard);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Command_Attack);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Command_Follow);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Command_Retreat);

	// Zone
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zone_Bridge);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zone_Gate);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zone_HighGround);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zone_Chokepoint);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zone_ResourceCamp);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Zone_RallyPoint);

	// Damage
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Physical);

	// Perk.Category
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Perk_Category_Hero);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Perk_Category_Army);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Perk_Category_Defense);

	// Roots whose leaves are added by the owning feature.
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feedback);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Modifier_Encounter);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Lane);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resource);
	CASTLEDEFENDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tutorial_Gate);
}
